.PONY: exllamav2
exllama:
	@echo "Creating virtual environment..."
	@conda env create --name exllamav2 --file exllamav2.yml
	@echo "Virtual environment created."

.PONY: run
run:
	@echo "Running exllamav2..."
	bash run.sh
	@echo "exllamav2 run."
